[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
coinpetitive = "7RUA3ry7n4ELZpMA4TwQBMmiHTKEhwSqML5xywM4m2pr"

[programs.devnet]
coinpetitive = "7RUA3ry7n4ELZpMA4TwQBMmiHTKEhwSqML5xywM4m2pr"

[registry]
url = "http://localhost:8899"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
start-validator = "solana-test-validator --reset --bpf-program 7RUA3ry7n4ELZpMA4TwQBMmiHTKEhwSqML5xywM4m2pr ./target/deploy/coinpetitive.so"
test-local = "anchor test --provider.cluster localnet"
