[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
coinpetitive = "CZ9rbEqcWAibvYdrJoFWKWqRhn2PHwWocRZU4erTcGfJ"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
url = "https://api.devnet.solana.com"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

