[package]
name = "coinpetitive"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = "0.26.0"

[features]
default = ["full"]
full = ["anchor-lang", "anchor-spl"]